# Generated by Django 4.2.1 on 2023-05-09 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_remove_seeker_age'),
    ]

    operations = [
        migrations.AddField(
            model_name='seeker',
            name='age',
            field=models.IntegerField(blank=True, null=True, verbose_name=range(1, 50)),
        ),
    ]
