# Generated by Django 4.2.1 on 2023-05-09 18:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_rename_is_seeker_user_is_seeker'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='knowledge_area',
            new_name='KnowledgeArea',
        ),
    ]
