# Generated by Django 4.2.1 on 2023-05-11 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_recruiter_bio_recruiter_city_recruiter_organization_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recruiter',
            name='social_youtube',
        ),
        migrations.RemoveField(
            model_name='seeker',
            name='social_youtube',
        ),
        migrations.AlterField(
            model_name='seeker',
            name='age',
            field=models.IntegerField(blank=True, null=True, verbose_name=range(1, 75)),
        ),
    ]
