# Generated by Django 4.2.1 on 2023-05-11 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_seeker_email_seeker_name_seeker_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='recruiter',
            name='email',
            field=models.EmailField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='recruiter',
            name='name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='recruiter',
            name='username',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
