# Generated by Django 4.2.1 on 2023-05-11 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_recruiter_email_recruiter_name_recruiter_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seeker',
            name='cv',
            field=models.TextField(max_length=5000, null=True),
        ),
    ]
