# Generated by Django 4.2.1 on 2023-05-12 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_alter_recruiter_organization'),
    ]

    operations = [
        migrations.AddField(
            model_name='seeker',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
