# Generated by Django 4.2.1 on 2023-05-15 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0028_alter_user_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seeker',
            name='cv',
            field=models.FileField(null=True, upload_to='uploads/'),
        ),
    ]
