# Generated by Django 4.2.7 on 2023-12-10 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0044_project_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='seeker',
            name='profileViews',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
