# Generated by Django 4.2.1 on 2023-12-15 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0045_seeker_profileviews'),
    ]

    operations = [
        migrations.CreateModel(
            name='NumberOfViews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField(default=0)),
            ],
        ),
        migrations.RemoveField(
            model_name='seeker',
            name='profileViews',
        ),
        migrations.AddField(
            model_name='seeker',
            name='numPOffers',
            field=models.IntegerField(null=True, verbose_name=range(1, 200)),
        ),
    ]
