# Generated by Django 4.2.1 on 2023-12-15 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0046_numberofviews_remove_seeker_profileviews_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='seeker',
            name='education',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
