# Generated by Django 4.2.1 on 2023-12-15 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0047_seeker_education'),
    ]

    operations = [
        migrations.AddField(
            model_name='seeker',
            name='visible_for_search',
            field=models.BooleanField(default=True),
        ),
    ]
