# Generated by Django 4.2.1 on 2023-10-10 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Seeker', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='applications',
            name='is_new',
            field=models.BooleanField(default=True),
        ),
    ]
