# Generated by Django 4.2.1 on 2023-06-07 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Recruiter', '0008_alter_jobpost_contact_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobpost',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='jobpost',
            name='organaization',
            field=models.CharField(max_length=200),
        ),
    ]
