# Generated by Django 4.2.1 on 2023-06-07 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Recruiter', '0009_alter_jobpost_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobpost',
            name='Requirements_and_skills',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='jobpost',
            name='Responsibilities',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='jobpost',
            name='job_brief',
            field=models.TextField(null=True),
        ),
    ]
