# Generated by Django 4.2.1 on 2023-06-07 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Recruiter', '0011_alter_jobpost_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobpost',
            name='job_brief',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
