# Generated by Django 4.2.1 on 2023-06-07 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Recruiter', '0015_alter_jobpost_organaization_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobpost',
            name='average_salary',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
