# Generated by Django 4.2.1 on 2023-06-08 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Recruiter', '0020_skillcategory_alter_dictionary_skill_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobpost',
            name='soft_skills',
            field=models.TextField(null=True),
        ),
    ]
