# Generated by Django 4.2.1 on 2023-05-09 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_city_skill_seeker_city'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='skill',
            name='created',
        ),
        migrations.AlterField(
            model_name='skill',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
