# Generated by Django 4.2.1 on 2023-05-09 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_remove_skill_created_alter_skill_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seeker',
            name='location',
        ),
        migrations.AlterField(
            model_name='seeker',
            name='cv',
            field=models.TextField(blank=True, max_length=5000, null=True),
        ),
    ]
