# Generated by Django 4.2.1 on 2023-05-09 18:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_seeker_age'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='is_seeker',
            new_name='is_Seeker',
        ),
    ]
