# Generated by Django 4.2.1 on 2023-05-11 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_remove_recruiter_social_youtube_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='seeker',
            name='email',
            field=models.EmailField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='seeker',
            name='name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='seeker',
            name='username',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
