# Generated by Django 4.2.1 on 2023-05-13 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0019_recruiter_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seeker',
            name='profile_image',
            field=models.ImageField(blank=True, default='image/profile/user-default.png', null=True, upload_to=''),
        ),
    ]
