# Generated by Django 4.2.1 on 2023-05-15 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0024_user_email_verified'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recruiter',
            name='email',
            field=models.EmailField(blank=True, max_length=500, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='seeker',
            name='cv',
            field=models.FileField(null=True, upload_to='static/CV'),
        ),
        migrations.AlterField(
            model_name='seeker',
            name='email',
            field=models.EmailField(blank=True, max_length=500, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
