# Generated by Django 4.2.1 on 2023-05-18 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0033_alter_seeker_cv'),
    ]

    operations = [
        migrations.AddField(
            model_name='seeker',
            name='cv_skills',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
