# Generated by Django 4.2.1 on 2023-06-08 20:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0039_alter_skill_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seeker',
            name='knowledge_area_id',
        ),
    ]
