# Generated by Django 4.2.1 on 2023-06-07 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Recruiter', '0007_remove_jobpost_is_active_jobpost_contact_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobpost',
            name='contact_email',
            field=models.EmailField(max_length=254, null=True),
        ),
    ]
