# Generated by Django 4.2.1 on 2023-06-07 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Recruiter', '0010_jobpost_requirements_and_skills_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobpost',
            name='description',
            field=models.TextField(null=True),
        ),
    ]
