# Generated by Django 4.2.1 on 2023-06-08 17:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Recruiter', '0023_alter_jobpost_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobpost',
            name='description',
        ),
    ]
