# Generated by Django 4.2.1 on 2023-09-19 11:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0044_project_link'),
        ('Recruiter', '0024_remove_jobpost_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='sentOffers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jobpost', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Recruiter.jobpost')),
                ('seeker', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.seeker')),
            ],
        ),
    ]
