# Generated by Django 4.2.1 on 2023-09-19 23:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Recruiter', '0027_jobpost_is_active'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Applications',
        ),
    ]
