# Generated by Django 4.2.1 on 2023-10-10 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Recruiter', '0028_delete_applications'),
    ]

    operations = [
        migrations.AddField(
            model_name='offers',
            name='is_new',
            field=models.BooleanField(default=True),
        ),
    ]
