# Generated by Django 4.2.1 on 2023-12-14 19:43

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Recruiter', '0029_offers_is_new'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobpost',
            name='month_year',
            field=models.CharField(default='2023-12', help_text='Format: YYYY-MM', max_length=7, validators=[django.core.validators.RegexValidator(code='invalid_year_month', message='Format must be YYYY-MM', regex='^\\d{4}-\\d{2}$')]),
        ),
    ]
