# Generated by Django 4.2.1 on 2023-12-14 19:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0045_seeker_profileviews'),
        ('Recruiter', '0030_jobpost_month_year'),
    ]

    operations = [
        migrations.CreateModel(
            name='TopCandidates',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Recruiter.jobpost')),
                ('seekers', models.ManyToManyField(to='accounts.seeker')),
            ],
        ),
    ]
